<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="Users.aspx.cs" Inherits="TimeTrax.Users" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
       <div id="divNotAuthorized" runat="server" visible="false">
        <asp:Label ID="Label3" runat="server" Text="Sorry, your user role does not allow access to this option."></asp:Label>

    </div>
    <div id="divAuthorized" runat="server" visible="false">
        <div runat="server" id="divAddUser" visible="false">
            <asp:Label ID="Label1" runat="server" Text="Enter Employee Name" Width="175px"></asp:Label>
            <asp:Label ID="Label2" runat="server" Text="Email Address" Width="175px"></asp:Label>
            <asp:Label ID="Label4" runat="server" Text="Manager User ID" Width="175px"></asp:Label>
            <asp:Label ID="Label5" runat="server" Text="UserLevel" Width="175px"></asp:Label>
            <asp:Label ID="Label6" runat="server" Text="CostPerHour" Width="175px"></asp:Label><br />

            <asp:TextBox ID="txtAddEmployeeName" runat="server" Text="" ></asp:TextBox>
            <asp:TextBox ID="txtAddEmailAddress" runat="server" Text=""></asp:TextBox>
            <asp:TextBox ID="txtAddManagerID" runat="server" Text=""></asp:TextBox>
            <asp:DropDownList ID="ddlUserLevel" runat="server"></asp:DropDownList>
            <asp:TextBox ID="txtAddCostPerHour" runat="server" Text=""></asp:TextBox>
            <asp:Button ID="btnAddThisUser" runat="server" Text="Add this User" OnClick="btnAddThisUser_Click" />
        </div>
        <div runat="server" id="divMessage" visible="false">
            <asp:Label ID="lblMessageBox" runat="server" Text=""></asp:Label>
            <asp:Button ID="btnOK" runat="server" Text="OK"  OnClick="btnOK_Click"/>
        </div>
        <asp:Button ID="btnShowAddUser" runat="server" Text="Add New User" OnClick="btnShowAddUser_Click" />
        <asp:GridView ID="GridView1" runat="server" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateColumns="False" 
            OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" DataKeyNames="ID" OnRowCancelingEdit="GridView1_RowCancelingEdit"
             AlternatingRowStyle-BackColor="Wheat" OnSorting="GridView1_Sorting" OnRowDeleting="GridView1_RowDeleting" >
            <Columns >
                 <asp:BoundField DataField="ID" HeaderText="ID"  HeaderStyle-BackColor="WindowFrame"  SortExpression="ID" ReadOnly="true"   />
                <asp:TemplateField HeaderText="EmployeeName" HeaderStyle-BackColor="WindowFrame" SortExpression="EmployeeName" >
                <ItemTemplate>
                <asp:Label ID="lblEmployeeName" runat="server" Text='<%#Eval("EmployeeName")%>'></asp:Label>
                 </ItemTemplate>
                <EditItemTemplate>
                <asp:TextBox ID="txtEmployeeName" runat="server" Text='<%#Eval("EmployeeName")%>' BackColor="Highlight"></asp:TextBox>
                </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="EmailAddress"  HeaderStyle-BackColor="WindowFrame"  SortExpression="EmailAddress">
                <ItemTemplate>
                <asp:Label ID="lblEmailAddress" Width="100%" runat="server" Text='<%#Eval("EmailAddress")%>'></asp:Label>
                 </ItemTemplate>
                <EditItemTemplate>
                <asp:TextBox ID="txtEmailAddress" Width="100%" runat="server" Text='<%#Eval("EmailAddress")%>'  BackColor="Highlight"></asp:TextBox>
                </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="ManagerID"  HeaderStyle-BackColor="WindowFrame"  SortExpression="ManagerID">
                <ItemTemplate>
                <asp:Label ID="lblManagerID" runat="server" Text='<%#Eval("ManagerID")%>'></asp:Label>
                 </ItemTemplate>
                <EditItemTemplate>
                <asp:TextBox ID="txtManagerID" runat="server" Text='<%#Eval("ManagerID")%>'  BackColor="Highlight"></asp:TextBox>
                </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="UserLevel"  HeaderStyle-BackColor="WindowFrame"  SortExpression="UserLevel">
                <ItemTemplate>
                <asp:Label ID="lblUserLevel" runat="server" Text='<%#Eval("UserLevel")%>'></asp:Label>
                 </ItemTemplate>
                <EditItemTemplate>
                <asp:TextBox ID="txtUserLevel" runat="server" Text='<%#Eval("UserLevel")%>'  BackColor="Highlight"></asp:TextBox>
                </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="CostPerHour"  HeaderStyle-BackColor="WindowFrame"  SortExpression="CostPerHour">
                <ItemTemplate>
                <asp:Label ID="lblCostPerHour" runat="server" Text='<%#Eval("CostPerHour")%>'></asp:Label>
                 </ItemTemplate>
                <EditItemTemplate>
                <asp:TextBox ID="txtCostPerHour" runat="server" Text='<%#Eval("CostPerHour")%>'  BackColor="Highlight"></asp:TextBox>
                </EditItemTemplate>
                </asp:TemplateField>

            </Columns>
        </asp:GridView>
    
    </div>
</asp:Content>